apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- ../../base

nameSuffix: -bot2

commonLabels:
  app: freqtrade-bot2

secretGenerator:
- name: freqtrade-secret
  behavior: merge
  literals:
  - FREQTRADE__STRATEGY=Strategy002

configMapGenerator:
- name: freqtrade-strategies
  behavior: replace
  files: 
  - Strategy002.py

patches:
  - path: ingress.yaml
    target:
      kind: HTTPRoute
